name: SquidHQ
main: com.squidhq.reef.Reef
version: 1.0.3-Reef
softdepend: [PlaceholderAPI]
commands:
  sqcheck:
    description: Check whether a given player is running the SquidHQ client
    usage: /sqcheck <name/uuid>
    permission: squidhq.check
  sqstats:
    description: Check the current online player stats
    usage: /sqstats
    permission: squidhq.stats
  sqreload:
    description: Reloads the plugin's configuration
    usage: /sqreload
    permission: squidhq.reload

permissions:
  squidhq.stats:
    default: op
    description: Allows use of /sqstats
  squidhq.check:
    default: op
    description: Allows use of /sqcheck
  squidhq.reload:
    default: op
    description: Allows use of /sqreload