
#   __             _     _         ____   #
#  / _\ __ _ _   _(_) __| | /\  /\/___ \  #
#  \ \ / _` | | | | |/ _` |/ /_/ //  / /  #
#  _\ \ (_| | |_| | | (_| / __  / \_/ /   #
#  \__/\__, |\__,_|_|\__,_\/ /_/\___,_\   #
#         |_|                             #

# These actions will be run when the player logs in.
# Valid placeholders: https://github.com/masterdoctor/SquidHQ-plugin/wiki/Placeholders
login:
  # These actions will be performed if the player who logs in is using the SquidHQ Client
  squid-client:
    # These messages will be sent without a prefix so that you can add your own.
    messages:
    - '&e&lSquidHQ  &eThanks for using the SquidHQ client!'

    commands:
    - 'give {player} diamond 1'

  # These actions will be performed if the player who logs in is using the vanilla (or another non-squid client)
  vanilla-client:
    messages:
    - '&e&lSquidHQ  &eWe recommend that you use the SquidHQ client! You can learn more at &6&nhttps://squidhq.com/&e.'

    # If you want to disable a feature that this plugin has, just close the section by setting it equal to []
    # Be sure to remove or comment up the list items that were in the section.
    commands: []



# Internal plugin data (please ignore)
config-version: 1


# Thanks for supporting SquidHQ!